const DEFAULT_PLAN_CODE = "free";
const DEFAULT_PLAN_DURATION_DAYS = 30;

const PLAN_ORDER = ["free", "standard", "pro", "premium"];
const PAID_PLAN_CODES = ["standard", "pro", "premium"];

const PLAN_ALIASES = {
  "premium-monthly": "premium",
  "premium-yearly": "premium",
  professional: "pro",
  blue: "pro",
};

const PLAN_DEFINITIONS = {
  free: {
    code: "free",
    label: "Free",
    priceBaht: 0,
    monthlyLimit: 50,
    allowSearchHistory: false,
    searchHistoryRetentionDays: 0,
    useAI: false,
    useInternet: false,
    internetMode: "none",
    maxInternetSources: 0,
    detailLevel: "template",
    sourceLimit: 10,
    allowDeepAnalysis: false,
    aiSourceLimit: 0,
    referenceLimit: 3,
    strictSourceFiltering: true,
    preferDatabaseOnlyForLawSections: true,
    followUpStrength: "basic",
    planSummary: "ค้นฐานข้อมูลอย่างเดียว เหมาะกับทดลองใช้งาน",
    highlights: [
      "ค้นหาจากฐานข้อมูลภายในระบบ",
      "ไม่ใช้ AI และไม่ใช้อินเทอร์เน็ต",
      "ไม่เก็บประวัติการค้นหา",
    ],
    isPurchasable: false,
    economyMode: {
      enabled: false,
      alwaysUseAI: false,
      strongDbThreshold: 18,
      simpleQuestionThreshold: 12,
      defaultAiThreshold: 12,
      skipCurrentOrExternal: false,
    },
  },
  standard: {
    code: "standard",
    label: "Standard",
    priceBaht: 29,
    monthlyLimit: 100,
    allowSearchHistory: true,
    searchHistoryRetentionDays: 7,
    useAI: true,
    useInternet: false,
    internetMode: "none",
    maxInternetSources: 0,
    detailLevel: "brief",
    sourceLimit: 5,
    allowDeepAnalysis: false,
    aiSourceLimit: 2,
    referenceLimit: 2,
    summaryRange: "2 ถึง 4 ข้อ",
    detailRange: "2 ถึง 3 ข้อ",
    aiTimeoutMs: 4500,
    aiMaxOutputTokens: 220,
    aiSourceContextCharLimit: 550,
    strictSourceFiltering: true,
    preferDatabaseOnlyForLawSections: true,
    followUpStrength: "basic",
    planSummary: "เริ่มใช้ AI แบบกระชับ เน้นคำตอบสั้นและคุมต้นทุน",
    highlights: [
      "AI สรุปแบบสั้นและสะอาด",
      "เหมาะกับถามคำถามทั่วไปจากฐานข้อมูล",
      "เก็บประวัติการค้นหา 7 วัน",
    ],
    isPurchasable: true,
    economyMode: {
      enabled: true,
      alwaysUseAI: false,
      strongDbThreshold: 16,
      simpleQuestionThreshold: 10,
      defaultAiThreshold: 9,
      skipCurrentOrExternal: true,
    },
  },
  pro: {
    code: "pro",
    label: "Pro",
    priceBaht: 49,
    monthlyLimit: 250,
    allowSearchHistory: true,
    searchHistoryRetentionDays: 15,
    useAI: true,
    useInternet: true,
    internetMode: "limited",
    maxInternetSources: 2,
    detailLevel: "detailed",
    sourceLimit: 8,
    allowDeepAnalysis: false,
    aiSourceLimit: 4,
    referenceLimit: 4,
    summaryRange: "4 ถึง 5 ข้อ",
    detailRange: "3 ถึง 5 ข้อ",
    aiTimeoutMs: 5500,
    aiMaxOutputTokens: 320,
    aiSourceContextCharLimit: 700,
    strictSourceFiltering: false,
    preferDatabaseOnlyForLawSections: false,
    followUpStrength: "enhanced",
    planSummary: "คำตอบละเอียดขึ้น พร้อมถามต่อเนื่องและใช้อินเทอร์เน็ตแบบจำกัด",
    highlights: [
      "AI ตอบละเอียดขึ้นพร้อมเหตุผล",
      "ถามต่อเนื่องได้ดีขึ้น",
      "ค้นอินเทอร์เน็ตเมื่อข้อมูลในฐานยังไม่พอ",
      "เก็บประวัติการค้นหา 15 วัน",
    ],
    isPurchasable: true,
    economyMode: {
      enabled: true,
      alwaysUseAI: false,
      strongDbThreshold: 17,
      simpleQuestionThreshold: 11,
      defaultAiThreshold: 13,
      skipCurrentOrExternal: true,
    },
  },
  premium: {
    code: "premium",
    label: "Premium",
    priceBaht: 69,
    monthlyLimit: 500,
    allowSearchHistory: true,
    searchHistoryRetentionDays: 30,
    useAI: true,
    useInternet: true,
    internetMode: "full",
    maxInternetSources: 4,
    detailLevel: "deep",
    sourceLimit: 12,
    allowDeepAnalysis: true,
    aiSourceLimit: 4,
    referenceLimit: 5,
    summaryRange: "4 ถึง 5 ข้อ",
    detailRange: "4 ถึง 5 ข้อ",
    aiTimeoutMs: 6000,
    aiMaxOutputTokens: 340,
    aiSourceContextCharLimit: 750,
    strictSourceFiltering: false,
    preferDatabaseOnlyForLawSections: false,
    followUpStrength: "deep",
    planSummary: "วิเคราะห์เชิงลึก เชื่อมหลายแหล่ง และใช้อินเทอร์เน็ตได้เต็มกว่า",
    highlights: [
      "AI เชิงลึกพร้อมเปรียบเทียบหลายแหล่ง",
      "follow-up และวิเคราะห์ต่อเนื่องได้ดีที่สุด",
      "ค้นอินเทอร์เน็ตได้เต็มกว่าแพ็กเกจอื่น",
      "เก็บประวัติการค้นหา 30 วัน",
    ],
    isPurchasable: true,
    economyMode: {
      enabled: true,
      alwaysUseAI: false,
      strongDbThreshold: 18,
      simpleQuestionThreshold: 12,
      defaultAiThreshold: 15,
      skipCurrentOrExternal: true,
    },
  },
};

module.exports = {
  DEFAULT_PLAN_CODE,
  DEFAULT_PLAN_DURATION_DAYS,
  PLAN_ALIASES,
  PLAN_DEFINITIONS,
  PLAN_ORDER,
  PAID_PLAN_CODES,
};
