const DEFAULT_PLAN_CODE = "free";
const DEFAULT_PLAN_DURATION_DAYS = 30;

const PLAN_ORDER = ["free", "pro", "premium"];
const PAID_PLAN_CODES = ["pro", "premium"];

const PLAN_ALIASES = {
  standard: "pro",
  "premium-monthly": "premium",
  "premium-yearly": "premium",
  professional: "pro",
  blue: "pro",
};

const PLAN_DEFINITIONS = {
  free: {
    code: "free",
    label: "Free",
    priceBaht: 0,
    monthlyLimit: 50,
    allowAiPreview: true,
    aiPreviewMonthlyLimit: 5,
    allowSearchHistory: false,
    searchHistoryRetentionDays: 0,
    useAI: false,
    useInternet: false,
    internetMode: "none",
    maxInternetSources: 0,
    detailLevel: "template",
    sourceLimit: 12,
    allowDeepAnalysis: false,
    aiSourceLimit: 0,
    referenceLimit: 4,
    summaryRange: "4 ถึง 6 ข้อ",
    detailRange: "3 ถึง 4 ข้อ",
    strictSourceFiltering: true,
    preferDatabaseOnlyForLawSections: true,
    followUpStrength: "enhanced",
    planSummary: "เริ่มใช้ฐานข้อมูลได้เต็มที่ พร้อมลองคำตอบแบบ AI ใกล้เคียง Professional ฟรีเพื่อเห็นความต่างก่อนอัปเกรด",
    highlights: [
      "ค้นหาจากฐานข้อมูลภายในระบบแบบเร็วและตรงประเด็น",
      "ลองคำตอบแบบ AI ใกล้เคียง Professional ได้ฟรี 5 ครั้งต่อเดือน",
      "ไม่ใช้อินเทอร์เน็ต แต่จัดคำตอบให้อ่านง่ายขึ้น",
      "รองรับการถามต่อเนื่องจากเรื่องเดิมได้ดีขึ้น",
      "ไม่เก็บประวัติการค้นหา",
    ],
    isPurchasable: false,
    economyMode: {
      enabled: false,
      alwaysUseAI: false,
      strongDbThreshold: 18,
      simpleQuestionThreshold: 12,
      defaultAiThreshold: 12,
      skipCurrentOrExternal: false,
    },
  },
  pro: {
    code: "pro",
    label: "Professional",
    priceBaht: 49,
    monthlyLimit: 250,
    allowSearchHistory: true,
    searchHistoryRetentionDays: 15,
    useAI: true,
    useInternet: true,
    internetMode: "limited",
    maxInternetSources: 2,
    detailLevel: "detailed",
    sourceLimit: 8,
    allowDeepAnalysis: false,
    aiSourceLimit: 4,
    referenceLimit: 4,
    summaryRange: "4 ถึง 5 ข้อ",
    detailRange: "3 ถึง 5 ข้อ",
    aiTimeoutMs: 5500,
    aiMaxOutputTokens: 320,
    aiSourceContextCharLimit: 700,
    strictSourceFiltering: false,
    preferDatabaseOnlyForLawSections: false,
    followUpStrength: "enhanced",
    planSummary: "ใช้ AI แบบเต็มเวลา ตอบละเอียดขึ้น ถามต่อเนื่องดีขึ้น และค้นข้อมูลภายนอกได้แบบจำกัดเมื่อฐานข้อมูลยังไม่พอ",
    highlights: [
      "AI ตอบได้ต่อเนื่องโดยไม่ต้องคอยใช้สิทธิ์ทดลอง",
      "ตอบละเอียดขึ้น พร้อมเหตุผลและเงื่อนไขสำคัญมากกว่าฟรี",
      "ค้นข้อมูลภายนอกได้แบบจำกัดเมื่อข้อมูลในระบบยังไม่พอ",
      "เก็บประวัติการค้นหา 15 วัน",
    ],
    isPurchasable: true,
    economyMode: {
      enabled: true,
      alwaysUseAI: false,
      strongDbThreshold: 17,
      simpleQuestionThreshold: 11,
      defaultAiThreshold: 13,
      skipCurrentOrExternal: true,
    },
  },
  premium: {
    code: "premium",
    label: "Premium",
    priceBaht: 79,
    monthlyLimit: 500,
    allowSearchHistory: true,
    searchHistoryRetentionDays: 30,
    useAI: true,
    useInternet: true,
    internetMode: "full",
    maxInternetSources: 4,
    detailLevel: "deep",
    sourceLimit: 12,
    allowDeepAnalysis: true,
    aiSourceLimit: 4,
    referenceLimit: 5,
    summaryRange: "4 ถึง 5 ข้อ",
    detailRange: "4 ถึง 5 ข้อ",
    aiTimeoutMs: 6000,
    aiMaxOutputTokens: 340,
    aiSourceContextCharLimit: 750,
    strictSourceFiltering: false,
    preferDatabaseOnlyForLawSections: false,
    followUpStrength: "deep",
    planSummary: "วิเคราะห์เชิงลึก แยกเงื่อนไขและข้อยกเว้นได้ชัด พร้อมเชื่อมฐานข้อมูลภายในกับข้อมูลภายนอกเมื่อจำเป็น",
    highlights: [
      "AI เชิงลึกพร้อมเปรียบเทียบหลายแหล่งและอธิบายเพิ่มเติมได้ดีกว่า",
      "follow-up และวิเคราะห์ต่อเนื่องได้ดีที่สุด",
      "ค้นอินเทอร์เน็ตได้เต็มกว่าแพ็กเกจอื่น",
      "เก็บประวัติการค้นหา 30 วัน",
    ],
    isPurchasable: true,
    economyMode: {
      enabled: true,
      alwaysUseAI: false,
      strongDbThreshold: 18,
      simpleQuestionThreshold: 12,
      defaultAiThreshold: 15,
      skipCurrentOrExternal: true,
    },
  },
};

module.exports = {
  DEFAULT_PLAN_CODE,
  DEFAULT_PLAN_DURATION_DAYS,
  PLAN_ALIASES,
  PLAN_DEFINITIONS,
  PLAN_ORDER,
  PAID_PLAN_CODES,
};
